-- ============================================================================
-- SETUP — Faturas de Cartão de Crédito
-- Rode este script no Supabase → SQL Editor (cole tudo e clique em "Run").
-- Ele cria: a tabela de metadados, o bucket de arquivos e as políticas de acesso.
-- É seguro rodar mais de uma vez (usa IF NOT EXISTS / drop policy antes de criar).
-- ============================================================================

-- 1) TABELA DE METADADOS DAS FATURAS ----------------------------------------
create table if not exists public.fin_faturas (
  id          bigint generated by default as identity primary key,
  ano         integer     not null,
  mes         integer     not null,          -- 0 = Janeiro ... 11 = Dezembro (padrão do app)
  cartao      text        not null default '',
  file_path   text        not null,          -- caminho do arquivo dentro do bucket
  file_name   text        not null,          -- nome original do arquivo
  mime        text,                          -- tipo (application/pdf, image/jpeg, ...)
  tamanho     bigint,                        -- tamanho em bytes
  analise     jsonb,                         -- RESERVADO para o relatório da IA (fase futura)
  created_at  timestamptz not null default now()
);

-- índice para buscar rápido por mês
create index if not exists idx_fin_faturas_periodo
  on public.fin_faturas (ano, mes);

-- 2) POLÍTICAS DA TABELA (mesmo modelo aberto/anon usado pelo restante do app)
alter table public.fin_faturas enable row level security;

drop policy if exists "fin_faturas_all" on public.fin_faturas;
create policy "fin_faturas_all"
  on public.fin_faturas
  for all
  using (true)
  with check (true);

-- 3) BUCKET DE STORAGE (privado) --------------------------------------------
insert into storage.buckets (id, name, public)
values ('faturas', 'faturas', false)
on conflict (id) do nothing;

-- 4) POLÍTICAS DO STORAGE (acesso ao bucket 'faturas') ----------------------
drop policy if exists "faturas_select" on storage.objects;
create policy "faturas_select"
  on storage.objects for select
  using (bucket_id = 'faturas');

drop policy if exists "faturas_insert" on storage.objects;
create policy "faturas_insert"
  on storage.objects for insert
  with check (bucket_id = 'faturas');

drop policy if exists "faturas_delete" on storage.objects;
create policy "faturas_delete"
  on storage.objects for delete
  using (bucket_id = 'faturas');

-- ============================================================================
-- PRONTO. Depois de rodar, recarregue o app e teste a aba
-- "Faturas de Cartão de Crédito".
-- ============================================================================
